### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by MatteCrystal** [mathigatti/MusicVideoMaker#1]
So the my install process is as follows. 

1. Create new anaconda environment using python 2.6
2. Activate that environment 
3. navigate to MusicVideoMaker-Master
4. run pip install -r requirements.txt
5. this gives a ModuleNotFoundError: No module named 'Cython'
6. run pip install cython
7. run pip install -r requirements.txt
8. this gives error ModuleNotFoundError: No module named 'numpy'
9. pip install numpy
10. run pip install -r requirements.txt (finishes this time no error)
11. run python scenes_preprocessing.py samples/MidnightCity.mp4
12 . I revive this error 

```
Traceback (most recent call last):
  File "C:\Users\MatteCrystal\anaconda3\envs\Environment\lib\site-packages\msaf\pymf\vol.py", line 17, in <module>
    from scipy.misc.common import factorial
ImportError: cannot import name 'factorial'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scenes_preprocessing.py", line 4, in <module>
    from music_video import clean
  File "C:\Users\MatteCrystal\Videos\MusicVideoMaker-master\MusicVideoMaker-master\music_video.py", line 4, in <module>
    import msaf
  File "C:\Users\MatteCrystal\anaconda3\envs\Environment\lib\site-packages\msaf\__init__.py", line 25, in <module>
    from . import algorithms
  File "C:\Users\MatteCrystal\anaconda3\envs\Environment\lib\site-packages\msaf\algorithms\__init__.py", line 23, in <module>
    [importlib.import_module(module_name) for module_name in module_names]
  File "C:\Users\MatteCrystal\anaconda3\envs\Environment\lib\site-packages\msaf\algorithms\__init__.py", line 23, in <listcomp>
    [importlib.import_module(module_name) for module_name in module_names]
  File "C:\Users\MatteCrystal\anaconda3\envs\Environment\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\MatteCrystal\anaconda3\envs\Environment\lib\site-packages\msaf\algorithms\cnmf\__init__.py", line 10, in <module>
    from .segmenter import *
  File "C:\Users\MatteCrystal\anaconda3\envs\Environment\lib\site-packages\msaf\algorithms\cnmf\segmenter.py", line 7, in <module>
    from msaf import pymf
  File "C:\Users\MatteCrystal\anaconda3\envs\Environment\lib\site-packages\msaf\pymf\__init__.py", line 39, in <module>
    from .sivm_sgreedy import *
  File "C:\Users\MatteCrystal\anaconda3\envs\Environment\lib\site-packages\msaf\pymf\sivm_sgreedy.py", line 21, in <module>
    from .vol import *
  File "C:\Users\MatteCrystal\anaconda3\envs\Environment\lib\site-packages\msaf\pymf\vol.py", line 19, in <module>
    from scipy.misc import factorial
ImportError: cannot import name 'factorial'
```

**Comment by mathigatti** [comment]
Why python 2.6? Please try python 3.6 or newer

**Comment by mathigatti** [comment]
On the other hand the problem looks like msaf needs an old dated version of scipy, try downgrading scipy as specified [here](https://stackoverflow.com/questions/56250306/how-to-fix-this-error-while-using-statsmodels-importerror-cannot-import-name) doing something like this: `pip install scipy==1.2.0`

**Comment by ZeroCool940711** [comment]
@mathigatti I cant run it on Windows 10, using Python 3.7.6, I do have the right version of scipy but for some reason I can't run it, here is the error I'm getting.
```
D:\ZeroCool\Projects\Python\Otros\Machine Learning\Music Video Generation (AMV)\MusicVideoMaker>python scenes_preprocessing.py samples/MidnightCity.mp4

Extracting audio
MoviePy - Writing audio in temp/youtube_video_audio_20201008-194151.mp3
MoviePy - Done.
Identifying song sections
Splitting song based on sections
The syntax of the command is incorrect.
The syntax of the command is incorrect.
Moviepy - Running:
>>> "+ " ".join(cmd)
Moviepy - Command returned an error
Traceback (most recent call last):
  File "scenes_preprocessing.py", line 68, in <module>
    ffmpeg_extract_subclip(video, v_min, v_max, targetname=temp_video)
  File "D:\Python\lib\site-packages\moviepy\video\io\ffmpeg_tools.py", line 41, in ffmpeg_extract_subclip
    subprocess_call(cmd)
  File "D:\Python\lib\site-packages\moviepy\tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'samples/MidnightCity.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2020-03-13T23:40:41.000000Z
  Duration: 00:04:03.23, start: 0.000000, bitrate: 360 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 640x360 [SAR 1:1 DAR 16:9], 261 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2020-03-13T23:40:41.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 03/13/2020.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 95 kb/s (default)
    Metadata:
      creation_time   : 2020-03-13T23:40:41.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 03/13/2020.
temp/A/20201008-194302.mp4: No such file or directory
```

**Comment by mathigatti** [comment]
Hi, the message `temp/A/20201008-194302.mp4: No such file or directory` means that you don't have a folder called "A" inside the folder temp, you can try creating that manually first. Or there might be some issue with the paths because windows uses \ instead of /

**Comment by mathigatti** [comment]
There is a colab [here](https://colab.research.google.com/drive/1SlTTYvbazihw3nC442UpI8wBVEs68_qp#scrollTo=grCRErniHEVd) to try it out easily and check how to use it.
